project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "The Billboard Hot 100 #1 Songs: What the Top Tells Us About the Evolution of Music"
  author:
    - Tiffany Peverilla (tp2906)
    - Suvethika Kandasamy Mohana (sk5697)
  repo-url: https://github.com/tiffpvrl/billboard-hot-100
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


